#spring.rabbitmq.host=43.142.160.159
#spring.rabbitmq.port=5672
spring.rabbitmq.addresses=43.142.160.159:5671,43.142.160.159:5672,43.142.160.159:5673
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest


spring.profiles.active= dev